### ISSUE TITLE
Error because Maps2 is not installed

### ISSUE THREAD

**Issue by matin73** [jweiland-net/events2#114]
I have installed 3.6.0 and got error that model from map2 extension is missing!? But maps2 is only "suggested" and not "depends"??

**Comment by froemken** [comment]
Morning @matin73 

thank you for your report.
Can you please tell me where this error appears? Frontend? Backend? Which View?
Currently I can't reproduce it, either with Debug nor with Live mode.

The only part I have found is template of Location:
```
<f:if condition="{location.txMaps2Uid}">
	<m2:widget.poiCollection poiCollection="{location.txMaps2Uid}" override="{settings: {mapWidth: '100%', mapHeight: '300', zoom: '14'}}" />
</f:if>
```

But, if txMaps2Uid is empty the widget was not called. If you deactivate maps2 the TCA of txMaps2Uid isn't there, so it is empty, too, and widget was not called. So, do you have your own templates?

Since version 3.6.0 you can create your own link to location, maybe that helps you to prevent calling this widget. Or, you create your own template and remove that widget.

Nice greetings

Stefan

**Comment by matin73** [comment]
in frontend. "Auflistung aller termine". Widget ist no called. Plugin seem calling map2 model somewhere else ... there was error concerning reflection

**Comment by matin73** [comment]
this is full error message:

(1/2) #1278450972 TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException

Class JWeiland\Maps2\Domain\Model\PoiCollection does not exist. Reflection failed.

**Comment by matin73** [comment]
at TYPO3\CMS\Extbase\Reflection\ReflectionService->buildClassSchema('JWeiland\\Events2\\Domain\\Model\\Location')
in /var/www/vhosts/xxx.at/httpdocs/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php line 165

**Comment by ktallafus** [comment]
It also happens when saving a record in backend. Same error about class PoiCollection.
Seems to be caused from a property annotation in Domain/Model/Location while executing processDatamap_afterAllOperations hook.

**Comment by mattweb** [comment]
Same here when saving a record in backend.

**Comment by froemken** [comment]
Thank you for your help. Today I get the same error in backend while saving an event with connected location record. Perfect: Time for debugging and solving. I keep you informed.

**Comment by froemken** [comment]
Hello,

I have just uploaded events2 version 3.7.2.
Please update, check and keep me informed, if it works for you.

Stefan

**Comment by froemken** [comment]
OK...seems to be solved now. Thank you for supporting events2

Stefan
