### ISSUE TITLE
Error in log, when event without location

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#167]
When an event doesn't have a location I get the following error. As far as I can see a location is not mandatory. (TYPO3 v9.5.13; events2 v4.1.1)

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1298012500: Required argument "location" is not set for JWeiland\Events2\Controller\LocationController->show. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file /kunden/xxx/rp-hosting/aaa/bbb/typo3cms/typo3_src-9.5.4/typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php in line 414. Requested URL: https://my-domain.de/veranstaltungen/kalender/veranstaltungsort?tx_events2_events%%5Baction%%5D=show&tx_events2_events%%5Bcontroller%%5D=Location&cHash=51d14235999118308cf71f8e6b844434 `

**Comment by froemken** [comment]
Hello @Hobokens 

thank you for you issue.

Since version 2.2.8 I have various f:if conditions around the location links. I have just checked that in Properties.html and List.html. Maybe your templates are not up2date.

If the problem is still valid, re-open this ticket and send me the Row and Template-Filename where I may have forgotten to wrap it with f:if.

Stefan
