### ISSUE TITLE
cannot update fields in translated entries

### ISSUE THREAD

**Issue by ja-sk** [jweiland-net/events2#180]
Changing the time settings in the original entry does not update the time in the translation. But since the fields are locked in the translation you cant update them manually either.

It is also not possible to hide a translated entry since that field is locked as well. The list view will pretend to let you hide the entry but on the next page load its unhidden again.

**Comment by froemken** [comment]
Hello @ja-sk 

events2 is currently not 100% translatable, because of following Bug in TYPO3: https://review.typo3.org/c/Packages/TYPO3.CMS/+/64112/6

Extbase uses the UID of the translated event in day table which is wrong. It has to use the UID of the record in default language as you may know from pages->tt_content relations. In translated tt_content record the pid is always the UID of the page record in default language.

I currently have tried so solve this problem with deactivating all fields in translated record.

Maybe we implement our own translation handling when we implement TYPO3 10 compatibility

**Comment by froemken** [comment]
Hello @ja-sk 

I have just released version 8.0.0 with has a much better support for translated records. I found a really huge bug while querying translated records.

Thank you for your help

Stefan
