### ISSUE TITLE
Hardcoded link to "Neuen Ort beantragen" in FormField.html

### ISSUE THREAD

**Issue by wowawebdesign** [jweiland-net/events2#183]
In the file
EXT:events2/Resources/Private/Partials/Event/FormFields.html

in line 76:
<div><f:link.page pageUid="8460" title="Neuen Veranstaltungsort beantragen">Neuen Ort beantragen</f:link.page></div>

**Comment by froemken** [comment]
Hello @wowawebdesign 

I have created a new patch where I have removed this link completely, because this link links to a powermail form which has nothing to do with events2. If you still need something like that, please add it back into your own version of this template.

Nice greetings from germany

Stefan
