### ISSUE TITLE
No image description in image in event

### ISSUE THREAD

**Issue by FurtFan86** [jweiland-net/events2#270]
I have a question about the extension events2:
I would like to display the description of an image in the event. in the Poberties.html the image is rendered here:

```
<f:render section="renderImages" arguments="{event: day.event}" />
there are several view helpers described in images.html:
<f:section name="renderImagesOnly">
<f:section name="renderResource">
In the "renderResource", another distinction is made for video and image.
In the <f:section name="renderImagesOnly"> I assumed that I would find something there like. 
<f:if condition="{image.description}">
 <figcaption class="image-caption">
 {image.description}
 </figcaption>
 </f:if>
```

and then the description of the image is rendered. However, this does not seem to work, or rather, it does not seem to be provided for in the template. 

<f:debug>{event.images}</f:debug>

```
array(2 items)
0 => TYPO3\CMS\Extbase\Domain\Model\FileReferenceprototypemodified entity (uid=39, pid=3)
uidLocal => protected38 (integer)
originalResource => protectedTYPO3\CMS\Core\Resource\FileReferenceprototypeobjectmodified
uid => protected39 (integer)
_localizedUid => protected39 (integer)modified
_languageUid => protected0 (integer)modified
_versionedUid => protected39 (integer)modified
pid => protected3 (integer)
1 => TYPO3\CMS\Extbase\Domain\Model\FileReferenceprototypepersistent entity (uid=40, pid=3)
uidLocal => protected35 (integer)
originalResource => protectedNULL
uid => protected40 (integer)
_localizedUid => protected40 (integer)modified
_languageUid => protected0 (integer)modified
_versionedUid => protected40 (integer)modified
pid => protected3 (integer)
```
Noticeable: In the video item the property originalResource contains a value, in the said image item NULL

How does something like that happen?

**Comment by froemken** [comment]
Hello @FurtFan86 

with events2 it is possible to add two events2 plugins with different configuration onto the same page. That way you can show big event images as header slider and somewhere below (after navigation bar or breadcrumb) just the event properties. That's why we have different sizes and rendering definitions in fluid template. But by default all data incl. images will be displayed at the same position.

I just have added `<f:debug>{image.description}</f:debug>` at row 9 of Images.html and description was displayed. So currently I can not confirm your issue.

Just using `<f:debug>{event.images}</f:debug>` is a bad idea. You should rather debug each object in ObjectStorage itself (see my debug from above). Then you will see the properties of TYPO3 Core FileReference instead of Extbase FileReference. The OriginalResource property will be filled while calling the getter first. That's why it seems to be empty in your debug:

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/extbase/Classes/Domain/Model/FileReference.php#L51

TYPO3 Core FileReference contains many getter methods like getTitle() and getDescription() to retrieve the merged property of the file itself and the overwritten value from FileReference record. You will see a property `propertiesOfFileReference` which contains just the properties of the reference record and the property `mergedProperties` which will contain a merged version of all properties of the file and the reference. Open them to see the value of the description property. If it is NULL, no description was set in file or reference.

**Comment by FurtFan86** [comment]
Hello @froemken ,

Thank you for your message. I have added the condition to line 9

```
<f:if condition="{image.description}">
					<figcaption>
						{image.description}
					</figcaption>
```

 and now the description is also passed.

Thanks for your tips

**Comment by froemken** [comment]
Hello @FurtFan86 

that sounds good. Perfect.

So I'm closing this ticket now

Stefan
