### ISSUE TITLE
[TYPO3 11] events in march aren't displayed correctly

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/events2#326]
The date for an event which is in the month march isn't displayed.

I already set `'phpTimeZone' => 'Europe/Berlin',` and cleared the cache. 
It's a german website.

<img width="603" alt="Bildschirmfoto 2022-02-11 um 15 28 15" src="https://user-images.githubusercontent.com/57705869/153609476-d16b1a0c-5da5-4f7a-a165-2f7db5c88ad1.png">

**Comment by froemken** [comment]
Good morning @PhilippKuhlmay 

thank you for reporting this issue. I can re-produce this error. It's because of the change to \DateTimeImmutables.

I have solved this issue just a few days ago: https://github.com/jweiland-net/events2/commit/ae93b145c56bcf221798c9cb4f424065dc6eb094

Have a nice start into this new day

Stefan
