### ISSUE TITLE
settings.mergeRecurringEvents not available in detail view

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/events2#383]
Hi,

I merge recurring events and get in list view the start date and the end date. In detail view the variable `{settings.mergeRecurringEvents}` is always `0`. That's why I only get the start date, which is a bit confusing for users. It would be helpful to have an option in the detail view to show the start and end date for merged events.

TYPO3 10.4.32
events2 8.0.1

Regards
Hobokens

**Comment by froemken** [comment]
Hello @Hobokens 

in Day/Properties.html of 8.0.1 I don't render any from->until Date:

https://github.com/jweiland-net/events2/blob/8.0.1/Resources/Private/Partials/Day/Properties.html#L86

I expect, that you have created your own templates to solve this from->until issue.

In that case please use Setup TS:
`plugin.tx_events2.settings.mergeRecurringEvents = 1`

That way this setting is available in all pages.

Please re-open this ticket, if the problem is still not solved.

Stefan

**Comment by Hobokens** [comment]
Hello @froemken ,
perfect, this solved the problem. Thanks a lot for your help and the development of the great extension.
BTW: the most perfect solution would be if in a calendar for each recurring event could be set invidually whether all dates should be displayed individually or merged. :-)))

**Comment by froemken** [comment]
Hi @Hobokens 

I thought about that already, but I have to do a GROUP BY over all day records. Don't found a solution to implement that feature an a record basis.

Stefan
