### ISSUE TITLE
Required argument "event" is not set for JWeiland\Events2\Controller\DayController->show.

### ISSUE THREAD

**Issue by tzeier** [jweiland-net/events2#417]
On the Show Detail page i get the following error:

" #1298012500 TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException

Required argument "event" is not set for JWeiland\Events2\Controller\DayController->show."

How can I fix this?

(TYPO3 11.5.27, Events2 8.1.6)

**Comment by sfroemkenjw** [comment]
Hello @tzeier 

TYPO3 has deprecated the usage of SwitchableControllerActions. That's why we had to add a lot more Plugins to our extension. See also news extension: They have the same problem and created an own tab to the newContentElementWizard.
The problem with all these new plugins is, that you have to take care of all links from one plugin to the others.

Nice to see that you already have found a solution for you

Stefan

**Comment by tzeier** [comment]
I see. Means, I'll have to go throgh all my own template files and check for depreceated links... 
Thank you.
