### ISSUE TITLE
RequiredArgumentMissingException in detail View

### ISSUE THREAD

**Issue by SvenJuergens** [jweiland-net/events2#432]
I just noticed this, is this normal or did I forget to set something? 
Events2 has its own list view and a separate subpage as a detail page. Of course, you can also call this detail page in this way, but only then do I get the error: Required argument "event" is not set for JWeiland\Events2\Controller\DayController->show.

**Comment by sfroemkenjw** [comment]
Hello @SvenJuergens 

I remember that issue. Because of the TYPO3 change of removing the switchableControllerActions we had to split our plugin into 6 plugins now. Each plugin has its own plugin namespace now `tx_events2_list`, `tx_events2_show`, `tx_events2_management`, ...
With version 9.0.0 we have added an additional check, if `pidOfDetailPage` is set or not. If set we update the pluginnamespace to `show` automatically for you, else: it stays `list`.

So, please upgrade to 9.0.0 to get that solved.

Stefan
