### ISSUE TITLE
Extension settings broken

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/events2#439]
Settings in Install Tool broken

```
Undefined array key "propertyName" in /var/www/html/app/site/vendor/jweiland/events2/Classes/Hooks/EmStaticInfo.php line 44
```

TBH I would suggest dropping static_info_tables and just use the country API of v12!

**Comment by sfroemkenjw** [comment]
Hello @georgringer 

I remember that. It was a time where static_info_tables was not TYPO3 12 ready. So I have moved that into suggest area instead of required. My fault. 
As static_info_tables is TYPO3 12 ready now, I have moved that extension back to required section of composer and it works again.

Currenty I don't see a chance to migrate to country API. Sorry

Stefan
