### ISSUE TITLE
Empty country select box in location record

### ISSUE THREAD

**Issue by wowaTYPO3** [jweiland-net/events2#448]
In TYPO3 12.4.9 I installed sjbr/static-info-tables because of an exception in the extensions settings module, but if I create a new location record, the country select box is empty.

![2024-01-23_14-44-36](https://github.com/jweiland-net/events2/assets/343511/5b2670ca-7f48-41c6-997a-7f8d5384834d)

**Comment by sfroemkenjw** [comment]
Hello @wowaTYPO3 

yes I know. There was a problem that static_info_tables was not TYPO3 12 ready. That's why I have moved it from required to suggested for a limmited time.
With TYPO3 12 release and a compatible version of static_info_tables I have removed that dependency back to required in composer.json.

Have fun using events2 9.0.0

Stefan
